### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by AndreaBrg** [NellWatson/VNlytics-Prototype#1]
Hi, I'd like to set up something similar in my game, and I wanted to know if this project is still active.

I found this repo [here](https://lemmasoft.renai.us/forums/viewtopic.php?f=4&t=39864#p424833) and [here](https://lemmasoft.renai.us/forums/viewtopic.php?f=52&t=39857) but many of the links in the post no longer work and I cannot find the sample prototype.

Thank you so much.

**Comment by DipeshAggarwal** [comment]
Hey. I should be able to help. Please let me know if you have any question. The new, better written, version of VNlytics is here https://github.com/NellWatson/VNlytics

**Comment by NellInc** [comment]
Thank you, both. Here is the new repo. I will update that posting!

https://github.com/NellWatson/VNlytics

Warmly,

*Eleanor 'Nell' Watson *
*CEET CITP FBCS FICS FIAP FIKE FRSA FRSS FCMI FLS SMIEEE*

*IEEE AI Ethics MaestroPresident, European Responsible AI OfficeDoctoral
Researcher: Engineering, Gloucestershire*
*Initiator, EthicsNet, CulturalPeace, Endohazard, Pacha .org*

**Comment by NellInc** [comment]
The prototype for testing it here:
https://github.com/NellWatson/VNlytics-Prototype

**Comment by AndreaBrg** [comment]
@DipeshAggarwal @NellInc Thank you.

I need some clarification about the content of https://github.com/NellWatson/VNlytics. Does it also include the server-side code? Does it still work with Ren'Py?

I see that the prototype contains a [telemetry_ren.py](https://github.com/NellWatson/VNlytics-Prototype/blob/main/game/telemetry/telemetry_ren.py), but I'm not sure how that is integrated into the sample game.

**Comment by DipeshAggarwal** [comment]
Hey @AndreaBrg 

https://github.com/NellWatson/VNlytics is the server side component. You need to install NodeJS and MongoDB to run it.

And the new VNlytics-Prototype isn't done yet but you can use the documentation of VNlytics (server) and https://github.com/NellWatson/old-VNlytics-Prototype code from this to write something that will work.

Are you comfortable writing Python?

**Comment by AndreaBrg** [comment]
@DipeshAggarwal, thank you so much. Yes, I'm very used to Python, just new to Ren'Py.

I will take a look at what you shared.

**Comment by DipeshAggarwal** [comment]
@AndreaBrg Let me know if you need any help. I'm closing this for now.
